### ISSUE TITLE
CrazyEights Issue - Checkers Team 

### ISSUE THREAD

**Issue by melemai25** [rinvii/CrazyEights#10]
- Can't tell who's turn it is/should include an indicator 
- Can't have a dumb AI and smart AI in the same game
- (Not a Bug) please implement a TextView for recent game actions
- Smart AI not implemented
- Game soft lock if a smart AI is chosen
- Once you have too many cards they go off of the textview so you can't view them 
- If you set human player to anything other than player 0 it immediately restarts the game
- Points are not being tracked off

**Comment by doemily** [comment]
Fixed
